### PR TITLE
fix: Use placeholders for unknown bounds

### LINKED ISSUE #134: Incorrect range when loading thresholds not in dataset from URL
## Description

- If the user opens a URL that has thresholded features not in the current dataset, the range is shown as [0, 1] instead of the original range.

- There should be a fallback in the range slider if a min and max bound for the slider can't be found.
  - ex: `--`

### PR DESCRIPTION
**Pull request by ShrimpCryptid**
Problem
=======
Fixes #134, [Incorrect range when loading thresholds not in dataset from URL](https://github.com/allen-cell-animated/nucmorph-colorizer/issues/134).

Solution
========
- LabeledRangeSlider defaults to showing a `--` label when a bound is NaN.
- Changed default feature range to `[NaN, NaN]` for features from datasets that haven't been loaded yet.

## Type of change

* Bug fix (non-breaking change which fixes an issue)

Steps to Verify:
----------------
1. Open preview link: https://allen-cell-animated.github.io/nucmorph-colorizer/pr-preview/pr-157/?collection=https%3A%2F%2Fdev-aics-dtp-001.int.allencell.org%2Fdan-data%2Fcolorizer%2Fdata%2Ftest%2Fcollection.json&dataset=Test%203%20Custom%20Manifest&feature=feature&filters=feature%3Atest%2520unit%3A0%3A140%2Cfeature%3A%3A35%3A140&range=35%2C140&color=matplotlib-cool
1. Switch to the filters tab. Observe the new placeholders.
1. Change datasets to Test 1. The range values should update to their correct values.

Screenshots (optional):
-----------------------
Before: (note how bounds go from 0 to 1, even though this doesn't represent the selected range)
image

After:
image

### CODE REVIEW

File: src/components/LabeledRangeSlider.tsx [hunk 1]
```diff
@@ -159,6 +159,14 @@ export default function LabeledRangeSlider(inputProps: LabeledRangeSliderProps):
...
   }
 
+  // Use a placeholder if the min/max bounds are undefined
+  const minSliderLabel = Number.isNaN(props.minSliderBound)
+    ? "--"
+    : numberToStringDecimal(props.minSliderBound, props.maxDecimalsToDisplay);
+  const maxSliderLabel = Number.isNaN(props.maxSliderBound)
+    ? "--"
+    : numberToStringDecimal(props.maxSliderBound, props.maxDecimalsToDisplay);
+
```
[the remark this answers is not in the document]
Comment (ShrimpCryptid) [reply src/components/LabeledRangeSlider.tsx:170]: No strong reason, so I made a fix that uses `Number.NaN` as the default max and min values of the range sliders.

**Review by frasercl — APPROVED** [review]

File: src/components/LabeledRangeSlider.tsx [hunk 2]
```diff
@@ -105,7 +106,7 @@ const SliderLabel = styled.p<{ $disabled?: boolean }>`
  * separately from the min and max value bounds and acts as a suggested range.
  */
 export default function LabeledRangeSlider(inputProps: LabeledRangeSliderProps): ReactElement {
-  const props = { ...defaultProps, ...inputProps } as Required<LabeledRangeSliderProps>;
+  const props = { ...defaultProps, ...excludeUndefinedValues(inputProps) } as Required<LabeledRangeSliderProps>;
```
Comment (toloudis) [inline src/components/LabeledRangeSlider.tsx:109]: question: does this imply that you can't force a value to be explicitly undefined through inputProps?

**Review by toloudis — APPROVED** [review]
LGTM!  just one q about the excludeUndefinedValues thing

File: src/components/LabeledRangeSlider.tsx (hunk 2 above)
Comment (ShrimpCryptid) [reply src/components/LabeledRangeSlider.tsx:109]: Good question! Yes, at least for this instance. I was having an issue where the default values for `minSliderBounds` and `maxSliderBounds` were getting overridden by `undefined` input props.

Comment (ShrimpCryptid) [reply src/components/LabeledRangeSlider.tsx:109]: I could probably add in a manual check for those two properties, but it seemed like that might cause problems elsewhere too.
