### PR TITLE
fix: Incorrect range when loading non-default feature from URL without range parameter

### LINKED ISSUE #197: Bounds don't reset when loading new dataset
## Description

The color ramp slider's min and max values do not reset when swapping between datasets, even if the checkbox is disabled.

## Expected Behavior

- If "Keep range between datasets" is disabled, the ramp's min and max should reset to the min and max value of the newly-selected feature.

### PR DESCRIPTION
**Pull request by ShrimpCryptid**
Fixed a bug where loading any feature besides the first (default) feature in a dataset via the URL would cause it to use the default feature's color map range instead. This caused odd, unexpected coloring on initial load.

Also fixes #197!

This fixes the bug by using a local variable (`newFeatureName`) to get the feature's color ramp range, rather than the `featureName` state (which may not be updated).

To test:
- Broken build (should appear in bright cyan): https://dev-aics-dtp-001.int.allencell.org/nucmorph-colorizer/dist/index.html?collection=https%3A%2F%2Fdev-aics-dtp-001.int.allencell.org%2Fdan-data%2Fcolorizer%2Fdata%2Fcollection.json&dataset=Mama%20Bear&feature=Height&color=matplotlib-cool
- Fixed build: https://allen-cell-animated.github.io/nucmorph-colorizer/pr-preview/pr-202/?collection=https%3A%2F%2Fdev-aics-dtp-001.int.allencell.org%2Fdan-data%2Fcolorizer%2Fdata%2Fcollection.json&dataset=Mama%20Bear&feature=Height&color=matplotlib-cool

### CODE REVIEW

File: src/App.tsx [hunk 1]
```diff
@@ -459,10 +460,10 @@ function App(): ReactElement {
   );
 
   const updateFeature = useCallback(
-    async (newDataset: Dataset, newFeatureName: string): Promise<void> => {
+    async (newDataset: Dataset, newFeatureName: string): Promise<string> => {
```
Comment (frasercl) [inline src/App.tsx:463]: Does this need to be `async` at all? I don't see any `await` points

File: src/App.tsx [hunk 2]
```diff
@@ -480,6 +481,7 @@ function App(): ReactElement {
       }
 
       canv.setFeature(newFeatureName);
+      return newFeatureName;
```
Comment (frasercl) [inline src/App.tsx:484]: `newFeatureName` is an argument to this function and is never modified within its body. Could the caller just use the value they passed in rather than getting it back out of this function?

File: src/App.tsx (hunk 1 above)
Comment (ShrimpCryptid) [reply src/App.tsx:463]: Good catch, it doesn't.

File: src/App.tsx (hunk 2 above)
Comment (ShrimpCryptid) [reply src/App.tsx:484]: There's an early return statement that returns the existing `featureName` state if the new feature could not be found.

Comment (frasercl) [reply src/App.tsx:489]: Makes sense!

**Review by frasercl — APPROVED** [review]

File: src/App.tsx [hunk 3]
```diff
@@ -458,11 +459,16 @@ function App(): ReactElement {
     [replaceDataset]
   );
 
+  /** Attempts to update the current feature. Also updates the color ramp min/max if the feature has changed.
```
Comment (toloudis) [inline src/App.tsx:462]: Readability:  this comment.  What does "update" mean.  The function is already called updateFeature. Maybe it should be called attemptUpdateFeatureAndColorRamp ?  Info I would be looking for here:  why does it need an update? Update from what to what?  Like for example, it could say "this is called when we need to update an already loaded feature when a new dataset is loaded that contains the same feature."

**Review by toloudis — APPROVED** [review]
LGTM no showstoppers but I would consider clarifying one of the comments

File: src/App.tsx (hunk 3 above)
Comment (ShrimpCryptid) [reply src/App.tsx]: Ended up moving this into two separate methods, `replaceFeature` and `resetColorRampToDefaults`. I also had to move them higher up in `App.tsx`, because they were used before their declaration and it was causing another bug (!) in `replaceDataset`.

**Comment by ShrimpCryptid** [comment]
Rerequesting @toloudis and @frasercl because I renamed and moved a few methods.

**Review by toloudis — APPROVED** [review]
awesome!

File: src/App.tsx [hunk 4]
```diff
@@ -399,7 +446,16 @@ function App(): ReactElement {
...
+    [
+      dataset,
+      featureName,
+      canv,
+      currentFrame,
+      getUrlParams,
+      replaceFeature,
+      resetColorRampRangeToDefaults,
+      featureThresholds,
+    ]
```
Comment (frasercl) [inline src/App.tsx:458]: This makes me wonder how common a pattern it is to have hooks depend on upstream `useCallbacks` within the same component, especially since this dependency array has all of `replaceFeature`'s `useCallback` dependencies alongside `replaceFeature` itself. It's not something I've encountered (or perhaps it's an error I've been leaving around in my own React code?), though it makes perfect sense for it to be there rather than risk unexpected behavior in the future.

**Review by frasercl — APPROVED** [review]

File: src/App.tsx (hunk 4 above)
Comment (ShrimpCryptid) [reply src/App.tsx:458]: Thanks for the note! I've started putting `useCallbacks` into dependency arrays because, based on prior experience, not doing so can lead to unexpected consequences and bugs. As you said here, `replaceFeature` has shared dependencies with `replacedDataset` so it's strictly necessary to include it as a dependency, but this protects the behavior if `replaceFeature` ever adds additional dependencies.
