### PR TITLE
fix: Fix crash from `ax.dtick` NaN error

### LINKED ISSUE #291: Bad axes crash
## Description

https://github.com/allen-cell-animated/nucmorph-colorizer/assets/30200665/0118ad95-0c60-47fe-8821-c6a4f4e05172

UI repeatedly loaded, hit an error screen, and returned while I had the reprocessed Nucmorph dataset open.

I believe this was caused by an issue with the scatterplot axis, but I have no way to be sure.

Error messages:
> ax.dtick error: NaN
> THREE.WebGLRenderer: Context Lost.
> React Router caught the following error during render `ax.dtick error: NaN`

## Reproduction

_A minimal example that exhibits the behavior._

## Environment

_Any additional information about your environment. E.g. OS version, python version, browser etc._

### PR DESCRIPTION
**Pull request by ShrimpCryptid**
Problem
=======
*Estimated size: small, 10-15 minutes*

Closes #291, a crash with the error message `ax.dtick error: NaN` on certain datasets.

I think what was happening was that Plotly can handle _some_ `Infinity` or `NaN` values in input data, but fails when calculating the range of axis values to show if _all_ the values are `Infinity` or `NaN`. 

This happens in some datasets on certain frame + feature combinations, such as in the updated nucmorph datasets. The **time\*** feature fails on the first frame, when values are undefined for all the cells currently in frame.

(\*representing the age of a cell since mitosis)

I also opened up a related issue here: [#329, NaN in feature data is shown as Infinity once loaded.](https://github.com/allen-cell-animated/nucmorph-colorizer/issues/329)

Solution
========
- Unrepresentable `NaN` and `Infinity` values are now removed from scatter plot data before rendering.
- Adds a warning banner for when the plot rendering fails for any reason, and clears the plot.

## Type of change
* Bug fix (non-breaking change which fixes an issue)

Steps to Verify:
----------------
(Note: these datasets are pretty big, so they may take up to 10 seconds to load.)
1. Open the bugged build: https://dev-aics-dtp-001.int.allencell.org/nucmorph-colorizer/dist/index.html#/viewer?collection=https%3A%2F%2Fdev-aics-dtp-001.int.allencell.org%2Fdan-data%2Fcolorizer%2Fdata%2Fnucmorph-apr2024%2Fcollection.json&dataset=Mama+Bear&feature=time&tab=scatter_plot&scatter-range=all&scatter-x=time&scatter-y=volume
2. Note that all cells on the current frame have a value of `Infinity`.
3. Go to the scatter plot tab and change the range from **All time** to **Current frame**. The UI will crash.
4. Now open the preview link and repeat the above instructions. No error should occur. https://allen-cell-animated.github.io/nucmorph-colorizer/pr-preview/pr-330/#/viewer?collection=https%3A%2F%2Fdev-aics-dtp-001.int.allencell.org%2Fdan-data%2Fcolorizer%2Fdata%2Fnucmorph-apr2024%2Fcollection.json&dataset=Mama+Bear&feature=time&tab=scatter_plot&scatter-range=all&scatter-x=time&scatter-y=volume

## Screenshots:
**Video showing off the error banner (🔊):**

https://github.com/allen-cell-animated/nucmorph-colorizer/assets/30200665/b8663610-bf0e-4472-bb94-d4fcf94ce9a5

image

### CODE REVIEW

**Review by toloudis — APPROVED** [review]
sanitize func looks good!  Still wonder about putting a try/catch around Plotly.react as an extra insurance layer.

**Comment by ShrimpCryptid** [comment]
@toloudis Re-requesting because of the new error banner handler!

**Comment by meganrm** [comment]
General question: is the data on this app always going through your data conversion repo? Because if so, this seems like something you'd want to fix there instead of having to check it all on the front end

File: src/components/Tabs/ScatterPlotTab.tsx [hunk 1]
```diff
@@ -716,15 +740,31 @@ export default memo(function ScatterPlotTab(props: ScatterPlotTabProps): ReactEl
...
+        setIsRendering(false);
+        lastRenderedState.current = {
+          xAxisFeatureKey,
+          yAxisFeatureKey,
+          rangeType,
+          ...props,
+        };
+      });
+    } catch (error) {
+      console.error(error);
```
Comment (meganrm) [inline src/components/Tabs/ScatterPlotTab.tsx:754]: could you move your sanitizeNumericDataArrays into this block so you're only cleaning the data if it fails? and then if it fails a second time show the alert?

**Comment by ShrimpCryptid** [comment]
> General question: is the data on this app always going through your data conversion repo? Because if so, this seems like something you'd want to fix there instead of having to check it all on the front end

We still need to have a conversation with scientists about what the expected behavior is, but I think having NaN values is valid for certain features. (ex: age of a cell since mitosis is NaN for cells that are present on the first frame, since the time since mitosis is unknown for them.) The issue here is that Plotly can't render plots with *only* NaN/Infinity values, which can happen with certain range filters (like only showing the current frame, which happens to be a frame with only NaN values).

File: src/components/Tabs/ScatterPlotTab.tsx (hunk 1 above)
Comment (ShrimpCryptid) [reply src/components/Tabs/ScatterPlotTab.tsx:754]: The structure of how the plot is rendered might make that a bit difficult? Currently the data is being filtered by range at the start of `renderPlot`, and there are additional methods that take in the (sanitized) data and perform additional operations on it (for example, highlighting the currently selected object or track). That means that we'd have to perform all of those calculations twice, and I'd have to restructure the method to do the try/catch checking.

Do you think we're losing something from sanitizing the data preemptively?

**Review by toloudis — APPROVED** [review]

File: src/components/Tabs/ScatterPlotTab.tsx (hunk 1 above)
Comment (meganrm) [reply src/components/Tabs/ScatterPlotTab.tsx:754]: I was just trying to avoid mapping over the data more than is necessary,  I'm assuming these are pretty large arrays

**Review by meganrm — APPROVED** [review]

File: src/components/Tabs/ScatterPlotTab.tsx (hunk 1 above)
Comment (ShrimpCryptid) [reply src/components/Tabs/ScatterPlotTab.tsx:754]: That makes sense. I'll add a note to revisit this if it causes performance issues.
