### PR TITLE
fix: Plot tab search bar responds to enter, updates with track number

### LINKED ISSUE #316: Track search box clears instead of showing current track #; also should update when enter pressed
## Description

Track search box only sometimes shows the current track number (such as when clicking from the scatter plot). Also, it does not respond to Enter keypress.

## Expected Behavior

_What did you expect to happen instead?_

## Reproduction

_A minimal example that exhibits the behavior._

## Environment

_Any additional information about your environment. E.g. OS version, python version, browser etc._

### PR DESCRIPTION
**Pull request by ShrimpCryptid**
Problem
=======
Closes #316!

*Estimated review size: tiny, <5 minutes*

Solution
========
- Adds support for enter keypress to search.
- Search box stays up to date with current track number.

## Type of change
* Bug fix (non-breaking change which fixes an issue)
* New feature (non-breaking change which adds functionality)

Screenshots (optional):
-----------------------

**Video talk-through (🔊):**

https://github.com/allen-cell-animated/nucmorph-colorizer/assets/30200665/0d5396d7-89a8-43c7-9fa9-c38e1cdf6559

### CODE REVIEW

**Review by frasercl — APPROVED** [review]

File: src/components/Tabs/PlotTab.tsx [hunk 1]
```diff
@@ -51,13 +55,9 @@ export default function PlotTab(props: PlotTabProps): ReactElement {
               onChange={(event) => {
                 props.setFindTrackInputText(event.target.value);
               }}
+              onPressEnter={searchForTrack}
```
Comment (toloudis) [inline src/components/Tabs/PlotTab.tsx:58]: what does this do if the field is empty?

**Review by toloudis — APPROVED** [review]
LGTM! This is a nice enhancement

File: src/components/Tabs/PlotTab.tsx (hunk 1 above)
Comment (ShrimpCryptid) [reply src/components/Tabs/PlotTab.tsx:58]: It will try to search for a `NaN` track, which won't exist. Nothing will happen on the UI, since the track is invalid.

I will actually implement a quick check to ignore `""` just because I can.
